### ISSUE TITLE
test

### ISSUE THREAD

**Issue by luismy** [luismy/test#1]
test

**Comment by luismy** [comment]
```yaml
cat << EOF | kubectl apply -f -
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-allow-internet
spec:
  endpointSelector:
    matchLabels:
      {}
  egress:
    # Outside Cluster - Allow egress to any endpoint
    - toEntities:
        - world
    # In Cluster - Everything in the cluster
    - toEntities:
      - cluster
    # In Cluster - Kubernetes DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
---
```
